// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA349k3jk-pGSgN_6JHTP74tNRtqjX8jeU',
    appId: '1:1048617371757:web:b4a179f3dbdc4f6ba31764',
    messagingSenderId: '1048617371757',
    projectId: 'booking-app-93a7a',
    authDomain: 'booking-app-93a7a.firebaseapp.com',
    storageBucket: 'booking-app-93a7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrdeSLt5FpKo7Fi7cjzZ0yK3FVKOYX_s',
    appId: '1:1048617371757:android:0238ce923a32b91ea31764',
    messagingSenderId: '1048617371757',
    projectId: 'booking-app-93a7a',
    storageBucket: 'booking-app-93a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh1OoB1RqlE0hcGkBa9TBvsHEnJq7NSoQ',
    appId: '1:1048617371757:ios:d734be66e7b10f27a31764',
    messagingSenderId: '1048617371757',
    projectId: 'booking-app-93a7a',
    storageBucket: 'booking-app-93a7a.appspot.com',
    iosClientId: '1048617371757-qp0u2nn8r3f65ftbfd9j1tci2nsvse9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh1OoB1RqlE0hcGkBa9TBvsHEnJq7NSoQ',
    appId: '1:1048617371757:ios:d734be66e7b10f27a31764',
    messagingSenderId: '1048617371757',
    projectId: 'booking-app-93a7a',
    storageBucket: 'booking-app-93a7a.appspot.com',
    iosClientId: '1048617371757-qp0u2nn8r3f65ftbfd9j1tci2nsvse9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );
}
